application: disc2017
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# - url: /.well-known/acme-challenge
#   static_dir: letsencrypt

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /s
  static_dir: s
  secure: always

- url: .*
  script: disc2017.app
  secure: always

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?.*\.ai
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - /artwork/*

libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: "1.1.7"
- name: numpy
  version: "latest"
- name: jinja2
  version: "latest"
